spring.application.name=ServicioCompras
spring.cloud.config.uri=http://localhost:2222
spring.config.import=optional:configserver:
server.port=8081
eureka.client.serviceUrl.defaultZone=http://localhost:1111/eureka/

# Configuración de la base de datos PostgreSQL
spring.datasource.url=jdbc:postgresql://ep-calm-king-a2ipcv7c-pooler.eu-central-1.aws.neon.tech/capgeticket?user=capgeticket_owner&password=NbtUhiawj41o&sslmode=require
spring.datasource.driver-class-name=org.postgresql.Driver
spring.jpa.database-platform=org.hibernate.dialect.PostgreSQLDialect

#Obligo a cargar los datos del SQL. En teoria no hace falta pero...

spring.jpa.defer-datasource-initialization=true

# Logging y configuración de Spring MVC
logging.level.org.springframework.web.servlet.mvc.method.annotation=TRACE
spring.mvc.throw-exception-if-no-handler-found=true
spring.mvc.static-path-pattern=/**
spring.web.resources.add-mappings=false

# Configuración de Spring Batch
spring.batch.jdbc.initialize-schema=always
spring.batch.job.enabled=true
